### ISSUE TITLE
Suggestion: add some styling to avoid long text from overflowing

### ISSUE THREAD

**Issue by mclemente** [Zombiefleischer/pause-text#21]
The following would avoid long texts extending through the sidebar. The line height change spaces the wrapped text better.

```css
figure#pause figcaption {
	width: 50%;
	margin: auto;
	line-height: 24px;
}
```
